services:
  backend:
    build: ./trafficlight-controller
    ports: 
      - 3000:3000
    restart: always
  
  frontend:
    build: ./trafficlight-client
    ports:
      - 80:80
      - 443:443
    environment:
      - BACKEND=backend
    restart: always
    depends_on:
      - backend
  
  # gateway:
  #   image: caddy:alpine
  #   depends_on:
  #     - frontend
  #     - backend
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile:Z
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #     - 2019:2019